import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import { Raleway } from "next/font/google";
import { Nunito_Sans } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

const nunito = Nunito_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} flex w-full justify-center  overflow-x-hidden  bg-[#101010]`}
      >
        <Analytics />
        <Header />
        <div className="radial-gradient absolute top-[-15rem] -z-30 h-[30rem] w-full overflow-x-hidden rounded-full blur-[8rem] sm:h-[35rem] md:h-[40rem]"></div>
        {children}
      </body>
    </html>
  );
}
